### ISSUE TITLE
Answer for why should set the pc=0x0100 in test_roms

### ISSUE THREAD

**Issue by mohanson** [stianeklund/eighty-eighty#4]
Answer for:
https://github.com/stianeklund/eighty-eighty/blob/master/src/test.rs#L21

Because there is PSEUDO ORG INSTRUCTION in this line: https://github.com/superzazu/8080/blob/master/cpu_tests/8080PRE.MAC#L44

**Comment by mohanson** [comment]
I read your code and wrote my own i8080 emulator: https://github.com/mohanson/i8080, thanks.

**Comment by stianeklund** [comment]
@mohanson hehe thank you I didn't see your comment until now but thanks for the information. I think I will go back and update some of these to Rust 2018 and do some improvements to the code base.
